#!/bin/zsh

IFS=$'\n'       # make newlines the only separator
set -f          # disable globbing
for i in $(cat working_directories); do
    echo "$i"
    cd $i
    git remote update

    if [ git status -uno ]
    then
    git pull
    fi
    
    bu
done